ruby '2.3.1'

source 'https://rubygems.org'

gem 'sinatra'
gem 'data_mapper'
gem 'mysql2'
gem 'dm-mysql-adapter'
gem 'do_mysql', '~> 0.10.17'
gem 'dm-postgres-adapter'
gem 'rerun', '~> 0.11.0'
gem 'json', '~> 1.8', '>= 1.8.3'
